import { Geist, Geist_Mono , Montserrat} from "next/font/google";
import "./globals.css";

export const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});
export const metadata = {
  title: "Mortgage Calculator",
  description: "Generated by Storm",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
